
site_name: 若阳的备忘录
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/image/favicon.png
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.prune 
    - header.autohide
    - content.code.copy
    - content.code.select

  palette:    
    - media: "(prefers-color-scheme dark)"
      scheme: slate
      primary: blue
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: 开启日间模式

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 开启夜间模式

extra:
  homepage: https://www.luruoyang.com
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ruoyanglu
      name: ruoyanglu
  analytics:
    provider: google
    property: G-Q4DFFNKQER
  feedback:
      title: 这个页面有用吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 这个页面有用
          data: 1
          note: >-
            谢谢~
        - icon: material/emoticon-sad-outline
          name: 这个页面有待改进
          data: 0
          note: >-
            感谢你的反馈！

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: inline  pymdownx-inline
      line_spans: __span
  - pymdownx.superfences
